version: 2
registries:
  maven-github:
    type: maven-repository
    url: https://github-package-registry-mirror.gc.nav.no/cached/maven-release
    username: POSTMAN
    password: PAT
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns:
          - "*"
  # Maintain dependencies for gradle
  - package-ecosystem: "gradle"
    directory: "/"
    registries:
      - maven-github
      - maven-central
    schedule:
      interval: "weekly"
      time: "12:20"
      day: "wednesday"
      timezone: "Europe/Oslo"
    groups:
      gradle:
        patterns:
          - "*"