version: 2
registries:
  github:
    enabled: true
    type: nav-private
    url: https://maven.pkg.github.com/navikt/
    token: ${{ secrets.GITHUB_TOKEN }}
    username: x-access-token
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns:
          - "*"
  # Maintain dependencies for gradle
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "12:20"
      day: "wednesday"
      timezone: "Europe/Oslo"
    groups:
      gradle:
        patterns:
          - "*"