[metadata]
format.version = "1.1"

[versions]
dp-biblioteker = "2024.09.20-13.31.40516c678fde"
jackson = "2.17.2"
kotest = "5.9.1"
kotlin = "2.0.20"
ktor = "2.3.12"
testcontainer = "1.20.1"
junit = "5.10.2"
logback = "1.5.8"
flyway = "10.18.0"
mockk = "1.13.12"


[libraries]
# Utils
dp-biblioteker-image-utils = { group = "no.nav.dagpenger", name = "image-utils", version.ref = "dp-biblioteker" }
dp-biblioteker-oauth2-klient = { group = "no.nav.dagpenger", name = "oauth2-klient", version.ref = "dp-biblioteker" }
dp-biblioteker-ktor-klient-metrics = { group = "no.nav.dagpenger", name = "ktor-client-metrics", version.ref = "dp-biblioteker" }
dp-biblioteker-pdl-klient = { group = "no.nav.dagpenger", name = "pdl-klient", version.ref = "dp-biblioteker"}
dp-aktivitetslogg = { group = "no.nav.dagpenger", name = "aktivitetslogg", version = "20240412.29.afd090" }
kotlin-logging = { group = "io.github.microutils", name = "kotlin-logging", version = "3.0.5" }
konfig = { group = "com.natpryce", name = "konfig", version = "1.6.10.0" }

# logging
logback-core = { group = "ch.qos.logback", name = "logback-core", version.ref = "logback" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }

# Rapids and Rivers
rapids-and-rivers = { group = "com.github.navikt", name = "rapids-and-rivers", version = "2024082715011724763661.50d7efb40f0f" }
rapids-and-rivers-test = { group = "com.github.navikt", name = "tbd-libs", version = "2024.09.12-14.35-01398f50" }

# Database
flyway = { group = "org.flywaydb", name = "flyway-core", version.ref = "flyway" }
flyway-postgres = { group = "org.flywaydb", name = "flyway-database-postgresql", version.ref = "flyway" }
hikari = { group = "com.zaxxer", name = "HikariCP", version = "5.1.0" }
kotlinquery = { group = "com.github.seratch", name = "kotliquery", version = "1.9.0" }
postgresql-driver = { group = "org.postgresql", name = "postgresql", version = "42.7.4" }
testcontainer-postgresql = { group = "org.testcontainers", name = "postgresql", version.ref = "testcontainer" }

# Serialization
jackson-annotation = { group = "com.fasterxml.jackson.core", name = "jackson-annotations", version.ref = "jackson" }
jackson-core = { group = "com.fasterxml.jackson.core", name = "jackson-core", version.ref = "jackson" }
jackson-kotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin", version.ref = "jackson" }
jackson-datatype-jsr310 = { group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-jsr310", version.ref = "jackson" }

# Test
testcontainer = { group = "org.testcontainers", name = "testcontainers", version.ref = "testcontainer" }
kotest-assertions-core = { group = "io.kotest", name = "kotest-assertions-core-jvm", version.ref = "kotest" }
kotest-assertions-json = { group = "io.kotest", name = "kotest-assertions-json-jvm", version.ref = "kotest" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
mock-oauth2-server = { group = "no.nav.security", name = "mock-oauth2-server", version = "2.1.9" }

# Ktor
ktor-client-auth-jvm = { group = "io.ktor", name = "ktor-client-auth-jvm", version.ref = "ktor" }
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-jackson = { group = "io.ktor", name = "ktor-client-jackson", version.ref = "ktor" }
ktor-client-logging-jvm = { group = "io.ktor", name = "ktor-client-logging-jvm", version.ref = "ktor" }
ktor-client-mock = { group = "io.ktor", name = "ktor-client-mock", version.ref = "ktor" }
ktor-serialization-jackson = { group = "io.ktor", name = "ktor-serialization-jackson", version.ref = "ktor" }
ktor-server = { group = "io.ktor", name = "ktor-server", version.ref = "ktor" }
ktor-server-auth = { group = "io.ktor", name = "ktor-server-auth", version.ref = "ktor" }
ktor-server-auth-jwt = { group = "io.ktor", name = "ktor-server-auth-jwt", version.ref = "ktor" }
ktor-server-content-negotiation = { group = "io.ktor", name = "ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-status-pages = { group = "io.ktor", name = "ktor-server-status-pages", version.ref = "ktor" }
ktor-server-cio = { group = "io.ktor", name = "ktor-server-cio", version.ref = "ktor" }
ktor-server-metrics-micrometer = { group = "io.ktor", name = "ktor-server-metrics-micrometer", version.ref = "ktor" }
ktor-server-test-host = { group = "io.ktor", name = "ktor-server-test-host", version.ref = "ktor" }

[bundles]
jackson = ["jackson-datatype-jsr310", "jackson-core", "jackson-annotation", "jackson-kotlin"]
kotest-assertions = ["kotest-assertions-core", "kotest-assertions-json"]
ktor-client = ["ktor-client-auth-jvm", "ktor-client-cio", "ktor-client-jackson", "ktor-client-logging-jvm", "ktor-client-content-negotiation"]
ktor-server = ["ktor-server", "ktor-server-auth", "ktor-server-auth-jwt", "ktor-server-content-negotiation", "ktor-server-status-pages", "ktor-serialization-jackson"]
postgres = ["flyway","flyway-postgres", "hikari", "postgresql-driver", "kotlinquery"]
postgres-test = ["testcontainer", "testcontainer-postgresql"]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version = "6.25.0" }
shadow-jar = { id = "com.gradleup.shadow",  version =  "8.3.2" }
