name: Publish to GitHub Package Repository

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/wrapper-validation-action@v1.1.0
      - uses: gradle/gradle-build-action@v2.6.1
        env:
          # Eksluder test dependencies
          DEPENDENCY_GRAPH_INCLUDE_CONFIGURATIONS: compileClasspath|runtimeClasspath
        with:
          gradle-version: wrapper
          dependency-graph: generate-and-submit
          arguments: --configuration-cache test

      - name: Set release tag
        run: |
          export TAG_NAME="$(TZ="Europe/Oslo" date +%Y%m%d).$(echo $GITHUB_SHA | cut -c 1-6)"
          echo "RELEASE_TAG=$TAG_NAME" >> $GITHUB_ENV
      - uses: ncipollo/release-action@a2e71bdd4e7dab70ca26a852f29600c98b33153e # ratchet:ncipollo/release-action@v1
        with:
          tag: ${{ env.RELEASE_TAG }}
          generateReleaseNotes: true

      - name: publish
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_version: ${{ env.RELEASE_TAG }}
          ORG_GRADLE_PROJECT_githubUser: x-access-token
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}